#!/bin/sh
#/etc/init.d/stop-watchdog.sh:
# Use the "Magic Close" feature of the watchdog driver to disable the watchdog
# See Documentation/watchdog/watchdog-api.txt in the kernel tree.
# All we do is echo "V" into /dev/watchdog to disable the watchdog.

### BEGIN INIT INFO
# Provides:          stop-watchdog.sh
# Short-Description: Stop the watchdog reset driver
# Required-Start:    $all
# Required-Stop:     $all
# Should-Start:      
# Should-Stop:       
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
### END INIT INFO

[ -e /dev/watchdog ] && echo -n "V" > /dev/watchdog
